-- App ordering, category management, and recoverable change history.
alter table public.apps add column if not exists "sortOrder" integer not null default 0;
alter table public.apps add column if not exists "isPinned" boolean not null default false;
alter table public.apps add column if not exists "deletedAt" timestamptz;
alter table public.apps add column if not exists "updatedAt" timestamptz not null default now();

with ranked as (
  select id, (row_number() over (order by "createdAt", id) - 1)::integer as position
  from public.apps
)
update public.apps a set "sortOrder" = ranked.position
from ranked where a.id = ranked.id and a."sortOrder" = 0;

create table if not exists public.app_categories (
  id bigint generated by default as identity primary key,
  name text not null unique check (length(trim(name)) > 0),
  "sortOrder" integer not null default 0,
  "createdAt" timestamptz not null default now()
);

insert into public.app_categories (name, "sortOrder")
select category, row_number() over (order by category) - 1
from (select distinct category from public.apps where category is not null and trim(category) <> '') c
on conflict (name) do nothing;

create table if not exists public.app_history (
  id bigint generated by default as identity primary key,
  "appId" text not null,
  action text not null check (action in ('update', 'delete')),
  snapshot jsonb not null,
  "createdAt" timestamptz not null default now(),
  "changedBy" uuid default auth.uid()
);

alter table public.app_categories enable row level security;
alter table public.app_history enable row level security;
alter table public.apps enable row level security;

drop policy if exists "Authenticated users manage apps" on public.apps;
create policy "Authenticated users manage apps" on public.apps
  for all to authenticated using (true) with check (true);
drop policy if exists "Public can read active apps" on public.apps;
create policy "Public can read active apps" on public.apps
  for select using ("deletedAt" is null);

drop policy if exists "Public can read app categories" on public.app_categories;
create policy "Public can read app categories" on public.app_categories for select using (true);
drop policy if exists "Authenticated users manage app categories" on public.app_categories;
create policy "Authenticated users manage app categories" on public.app_categories
  for all to authenticated using (true) with check (true);
drop policy if exists "Authenticated users read app history" on public.app_history;
create policy "Authenticated users read app history" on public.app_history
  for select to authenticated using (true);

create or replace function public.capture_app_history()
returns trigger language plpgsql security definer set search_path = public as $$
declare history_action text;
begin
  if tg_op = 'UPDATE' then
    if old.title is not distinct from new.title
      and old.category is not distinct from new.category
      and old.url is not distinct from new.url
      and old."thumbnailUrl" is not distinct from new."thumbnailUrl"
      and old."isPinned" is not distinct from new."isPinned"
      and old."deletedAt" is not distinct from new."deletedAt" then
      new."updatedAt" = now();
      return new;
    end if;
    history_action = case when old."deletedAt" is null and new."deletedAt" is not null then 'delete' else 'update' end;
  else
    history_action = 'delete';
  end if;
  insert into public.app_history ("appId", action, snapshot, "changedBy")
  values (old.id::text, history_action, to_jsonb(old), auth.uid());
  if tg_op = 'DELETE' then return old; end if;
  new."updatedAt" = now();
  return new;
end;
$$;

drop trigger if exists apps_history_trigger on public.apps;
create trigger apps_history_trigger before update or delete on public.apps
for each row execute function public.capture_app_history();

create or replace function public.rename_app_category(old_name text, new_name text)
returns void language plpgsql security invoker set search_path = public as $$
begin
  if trim(new_name) = '' then raise exception 'Category name cannot be empty'; end if;
  if exists (select 1 from public.app_categories where name = trim(new_name) and name <> old_name) then
    raise exception 'Category already exists';
  end if;
  update public.apps set category = trim(new_name) where category = old_name;
  update public.app_categories set name = trim(new_name) where name = old_name;
end;
$$;

create or replace function public.delete_app_category(category_name text, replacement_name text default null)
returns void language plpgsql security invoker set search_path = public as $$
declare app_count integer;
begin
  select count(*) into app_count from public.apps where category = category_name and "deletedAt" is null;
  if app_count > 0 then
    if replacement_name is null or replacement_name = category_name
      or not exists (select 1 from public.app_categories where name = replacement_name) then
      raise exception 'A valid replacement category is required';
    end if;
    update public.apps set category = replacement_name where category = category_name;
  end if;
  delete from public.app_categories where name = category_name;
end;
$$;

create or replace function public.save_category_order(items jsonb)
returns void language sql security invoker set search_path = public as $$
  update public.app_categories c
  set "sortOrder" = x.position
  from jsonb_to_recordset(items) as x(name text, position integer)
  where c.name = x.name;
$$;

create or replace function public.save_app_order(items jsonb)
returns void language sql security invoker set search_path = public as $$
  update public.apps a
  set "sortOrder" = x.position
  from jsonb_to_recordset(items) as x(id text, position integer)
  where a.id::text = x.id;
$$;

create or replace function public.restore_app_history(history_id bigint)
returns void language plpgsql security invoker set search_path = public as $$
declare saved jsonb;
begin
  select snapshot into saved from public.app_history where id = history_id;
  if saved is null then raise exception 'History entry not found'; end if;

  update public.apps set
    title = saved->>'title',
    category = saved->>'category',
    url = saved->>'url',
    "thumbnailUrl" = coalesce(saved->>'thumbnailUrl', ''),
    "sortOrder" = coalesce((saved->>'sortOrder')::integer, 0),
    "isPinned" = coalesce((saved->>'isPinned')::boolean, false),
    "deletedAt" = null
  where id::text = saved->>'id';
end;
$$;

grant execute on function public.rename_app_category(text, text) to authenticated;
grant execute on function public.delete_app_category(text, text) to authenticated;
grant execute on function public.save_category_order(jsonb) to authenticated;
grant execute on function public.save_app_order(jsonb) to authenticated;
grant execute on function public.restore_app_history(bigint) to authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
    and not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'app_categories') then
    alter publication supabase_realtime add table public.app_categories;
  end if;
end $$;
